mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^results', views.results, name='results'),
    url(r'^vote/$', views.vote, name='vote'),
    url(r'^auth_view', views.auth_view, name='auth_view'),
    url(r'^register', views.register, name='register'),
    url(r'^logout/$', views.logout),
    url(r'^loggedin/$', views.loggedin),
    url(r'^admin_view/$', views.admin_view),
    url(r'^invalid_login', views.invalid_login),
    url(r'^detail/$', views.detail),
    url(r'^history/$', views.history),
    url(r'^forgot', views.forgot),
    url(r'^add_question', views.add_question),
    url(r'^upload_file', views.upload_file)
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    multi_answer = models.BooleanField(default=False)
    question_type = models.CharField(max_length=200, default='python')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_right = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text


class Test(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    number_of_correct_answer = models.IntegerField(default=0)
    number_of_incorrect_answer = models.IntegerField(default=0)
    data_passing = models.DateTimeField('date published')


class TestInfo(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    user_answer = models.CharField(max_length=200)
    right_answer = models.CharField(max_length=200)
    is_user_answered_right = models.BooleanField(default=False)

polls/views.py
import random

from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render, render_to_response

from .utils import handle_uploaded_file, get_results
from .models import Question, Test


def index(request):
    """ Render main page """
    return render(request, 'polls/index.html')


@login_required
def detail(request):
    """ Returns the required number of randomly selected questions  """
    list_ids_questions = [question.pk for question in Question.objects.all()]
    random.shuffle(list_ids_questions)
    number_questions = list_ids_questions[:settings.NUMBER_OF_QUESTION_PER_TEST]
    questions = [get_object_or_404(Question, pk=question_id) for question_id in number_questions]
    return render(request, 'polls/detail.html', {'questions': questions})


def results(request):
    """ Render page with current test result """
    return render(request, 'polls/results.html')


def vote(request):
    """ Handle current test """
    current_user = get_object_or_404(User, pk=request.user.pk)
    form_data = {
        int(question.split('_')[1]): [answer for answer in request.POST.getlist(question)]
        for question in request.POST.keys() if 'question_' in question
    }
    test_id = get_results(form_data, current_user)
    return render(
        request, 'polls/results.html',
        {'test': get_object_or_404(Test, pk=test_id)}
    )


def auth_view(request):
    """ Login user """
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        page = 'admin_view' if user.groups.filter(name='admin').exists() else 'loggedin'
        return HttpResponseRedirect(page)
    else:
        return HttpResponseRedirect('invalid_login')


def logout(request):
    """ Logout user ans redirect to the main page """
    auth.logout(request)
    return redirect('/polls')


@login_required
def loggedin(request):
    """ Render page with tests selection"""
    return render_to_response(
        'polls/loggedin.html',
        {
            'user': request.user,
            'is_admin': request.user.groups.filter(name='admin').exists()
        }
    )


@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def admin_view(request):
    """ Render page with results for all users """
    return render_to_response(
        'polls/admin_view.html',
        {
            'user': request.user,
            'is_admin': True,
            'tests': Test.objects.all()
        }
    )


def invalid_login(request):
    """ In case wrong auth data """
    return render(request, 'polls/invalid_login.html')


def register(request):
    """ Register a new user and redirect to page with tests selection """
    username = request.POST.get('id_username', '')
    email = request.POST.get('email', '')
    password = request.POST.get('id_password1', '')
    user = User.objects.create_user(username, email, password)
    user.save()
    auth.login(request, auth.authenticate(username=username, password=password))
    return HttpResponseRedirect('loggedin')


@login_required
def history(request):
    """ Render page with all tests for current user"""
    current_user = get_object_or_404(User, pk=request.user.pk)
    return render(request, 'polls/history.html', {'h': current_user})


# TODO
def forgot(request):
    """ Define user, using email address, and send email with password """
    # email = request.POST.get('email', '')
    # User.objects.filter(email=email)
    return render(request, 'polls/forgot.html')


@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def upload_file(request):
    """ Handle xml file for adding new questions """
    result = handle_uploaded_file(request.FILES['file'])
    return HttpResponseBadRequest(content='Please attach ONLY XML file') if result else render(
        request, 'polls/upload_file.html'
    )


@user_passes_test(lambda u: u.groups.filter(name='admin').exists())
def add_question(request):
    """ Render page for downloading file """
    return render(request, 'polls/add_question.html', {'is_admin': True})

polls/templates/polls/add_question.html
{% extends 'polls/base.html' %}
{% block content %}

<form action="upload_file" enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="input-group input-group-lg">
      <button id="fake-file-button-browse" type="button" class="btn btn-default" onclick="uploadFile();">Upload</button>
      <input type="file" name="file" style="display:none" id="files-input-upload">
      <input type="text" id="fake-file-input-name" disabled="disabled" placeholder="File not selected" class="form-control">
      <input type="submit" value="Отправить" class="btn btn-default">
   </div>
</form>
<br>
<div id="example">
   <h3>To add new questions, please create and download such .xml file</h3>
   <textarea readonly cols="60" rows="17"><?xml version="1.0" encoding="utf-8"?>
        <xml>
        <question question_text="Question 1?">
            <choice is_right="false">Choice 1</choice>
            <choice is_right="false">Choice 2</choice>
            <choice is_right="true">Choice 3</choice>
            <choice is_right="false">Choice 4</choice>
        </question>
        <question question_text="Question 2?">
            <choice is_right="false">Choice 1</choice>
            <choice is_right="false">Choice 2</choice>
            <choice is_right="true">Choice 3</choice>
            <choice is_right="false">Choice 4</choice>
        </question>
    </xml>
    </textarea>
</div>
{% endblock %}

polls/templates/polls/admin_view.html
{% extends 'polls/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>User Name</th>
                    <th>Data_passing</th>
                    <th>Number of correct answer</th>
                    <th>Number of incorrect answer</th>
                </tr>
                </thead>
                <tbody id="myTable">
                {% for test in tests %}
                {% if test.number_of_correct_answer > test.number_of_incorrect_answer %}
                <tr class="bg-success">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ test.user }}</td>
                    <td>{{ test.data_passing }}</td>
                    <td>{{ test.number_of_correct_answer }}</td>
                    <td>{{ test.number_of_incorrect_answer }}</td>
                </tr>
                {% else %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ test.user }}</td>
                    <td>{{ test.data_passing }}</td>
                    <td>{{ test.number_of_correct_answer }}</td>
                    <td>{{ test.number_of_incorrect_answer }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-12 text-center">
            <ul class="pagination pager" id="myPager"></ul>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/base.html
{% load staticfiles %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/loggedin.css' %}"/>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="{% static 'polls/add_question.js' %}"></script>

<section class="pt-5 pb-5 bg-light inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="mt-0 mb-3 text-secondary">Hi, {{user.username}}, logged in!</h1>
                <div class="breadcrumbs">
                    {% if is_admin%}
                    <p class="mb-0 text-secondary">Click
                        <a href="/polls/logout">here</a> to logout  /  
                        <a href="/polls/loggedin">Show page with tests</a>  /  
                        <a href="/polls/add_question">Add questions</a>  /  
                        <a href="/polls/admin_view">Show page with results</a>
                    </p>
                    {% else %}
                    <p class="mb-0 text-secondary">Click
                        <a href="/polls/logout">here</a> to logout  / 
                        <a href="/polls/history">Show my history</a>  /  
                        <a href="/polls/loggedin">Try again?</a>
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

<br><br>

{% block content %}
{% endblock %}

polls/templates/polls/detail.html
{% load staticfiles %}

<link href="//netdna.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

{% autoescape off %}
<div class="col-md-6">
<form action="{% url 'polls:vote'%}" method="post" name="quiz">
    <input type="hidden" name="csrfmiddlewaretoken" value={{csrf_token}}>
    <ol class="list-group">
        {% for question in questions %}
        {% if question.multi_answer %}
        <li class="list-group-item"><h3 class="question">{{ question.question_text }}</h3>
            {% for choice in question.choice_set.all %}
            <input type="checkbox" name="question_{{ question.id }}" value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </li>
        {%else%}
        <li class="list-group-item"><h3 class="question">{{ question.question_text }}</h3>
            {% if question.choice_set.count == 1 %}
            <input type="text" name="question_{{ question.id }}"/>
            {% else %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="question_{{ question.id }}" id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ol>
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary btn-lg active" onclick="checkChoice();">Submit</button>
                <br/>
            </div>
        </div>
    </div>
</form>
</div>
{% endautoescape %}

polls/templates/polls/forgot.html
{% load staticfiles %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form role="form" class="sign_up_form">
                <h2 class="sign_up_title">Reset password</h2>
                <p>Enter your email address we will sent you the password reset link.</p>
                <div class="form-group">
                    <input type="email" name="email" id="email" class="form-control input-lg"
                           placeholder="Email address" tabindex="4">
                </div>
                <div class="row">
                    <a href="/polls">
                        <div class="btn btn-primary btn-block btn-lg">Reset</div>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

polls/templates/polls/history.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Data_passing</th>
                    <th>Number of correct answer</th>
                    <th>Number of incorrect answer</th>
                </tr>
                </thead>
                <tbody id="myTable">
                {% for test in h.test_set.all %}
                {% if test.number_of_correct_answer > test.number_of_incorrect_answer %}
                <tr class="bg-success">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ test.data_passing }}</td>
                    <td>{{ test.number_of_correct_answer }}</td>
                    <td>{{ test.number_of_incorrect_answer }}</td>
                </tr>
                {% else %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ test.data_passing }}</td>
                    <td>{{ test.number_of_correct_answer }}</td>
                    <td>{{ test.number_of_incorrect_answer }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-12 text-center">
            <ul class="pagination pagination-lg pager" id="myPager"></ul>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
<script src="http://code.jquery.com/jquery-2.0.2.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="{% static 'polls/main.js' %}"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

<br>


<section class="container text-center">
    <div class="login">
        <h1><span id="formHeading">Login or </span><a id="formOption" onclick="formToggle()" href="#">Sign Up</a></h1>
        <br>
        <!--Login form-->
        <form id="login_form" name="login_form" method="post" action="auth_view">{% csrf_token %}
            <p hidden class="well" id="login_validation_errors"></p>
            <input id="login_user" type="text" name="username" value="" placeholder="Username"></br>
            <input id="login_password" type="password" name="password" value="" placeholder="Password"></br>
            <br>
            <input id="login_submit" type="submit" name="login_submit" value="Login">
        </form>
        <!--Signup form-->
        <form hidden name="signup_form" id="signup_form" action="register" method="post">{% csrf_token %}
            <p hidden class="well" id="signup_validation_errors"></p>
            <input id="signup_email" type="text" name="email" value="" placeholder="Email"></br>
            <input id="signup_username" type="text" name="id_username" value=""
                   placeholder="Username"></br>
            <input id="signup_password" type="password" name="id_password1" value="" placeholder="Password"></br>
            <input id="signup_submit" type="submit" value="Sign up">
        </form>
        <!--./signup form-->
        <hr>
        <p class="text-center">Forgot your password?<br> <a href="/polls/forgot.html">Click here to reset it</a>.</p>
    </div>
</section>

polls/templates/polls/invalid_login.html
{% load staticfiles %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/invalid_login.css' %}"/>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous">


<div class="container">
    <div class="jumbotron">
        <div class="text-center"><i class="fa fa-5x fa-frown-o" style="color:#d9534f;"></i></div>
        <h1 class="text-center">Your login details are invalid!</h1>
        <br/>
        <p class="text-center"><a class="btn btn-primary" href="/polls"><i class="fa fa-home"></i>&nbsp;&nbsp;&nbsp;Click to login again</a></p>
    </div>
</div>

polls/templates/polls/loggedin.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="col-md-4">
    <h2>Choose language</h2>
    <div class="form-check">
        <label>
            <input type="radio" name="radio" checked id="ph"> <span class="label-text"><a href="/polls/detail">Python</a></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="radio" id="js"> <span class="label-text">JS</span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="radio" id="db"> <span class="label-text">Database</span>
        </label>
    </div>
</div>
{% endblock %}

polls/templates/polls/logout.html
Log out

<p><a href="/polls">Main page</a></p>

polls/templates/polls/results.html
{% load filter %}
{% load staticfiles %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/loggedin.css' %}"/>

<section class="pt-5 pb-5 bg-light inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="mt-0 mb-3 text-secondary">{{ user.username }}, your result: </h1>
                <div class="breadcrumbs">
                    <p class="mb-0 text-secondary"><a href="/polls/loggedin">Try again?</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

<h2>Correct answer: {{ test.number_of_correct_answer }}</h2>
<br/>
<h2>Incorrect answer: {{ test.number_of_incorrect_answer }}</h2>
<br/>

{% autoescape off %}
<div class="col-md-6">
    <ol class="list-group">
        {% for testinfo in test.testinfo_set.all %}
        {% if testinfo.is_user_answered_right %}
        <li class="list-group-item list-group-item-success"><h5>{{ testinfo.question_text }}</h5>
            <p>Your answer: {{ testinfo.user_answer|json }}</p>
        </li>
        {% else %}
        <li class="list-group-item list-group-item-danger"><h5>{{ testinfo.question_text }}</h5>
            <p>Your answer: {{ testinfo.user_answer|json }}</p>
            <h6>Right answer: {{ testinfo.right_answer|json }}</h6>
        </li>
        {% endif %}
        {% endfor %}
    </ol>
</div>
{% endautoescape %}

polls/templates/polls/upload_file.html
<h3>Successful uploaded.</h3>
<br/>
<a href="/polls/loggedin">Show page with test</a>